### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by karola3vax** [festivaldev/Paradise#1] opened 2022-06-15 11:07 UTC
Build started...
NuGet Package restore failed for project Client\Paradise.Client: Unable to find version '11.2.1' of package 'YamlDotNet'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'YamlDotNet.11.2.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project Realtime\Paradise.Realtime: Unable to find version '2.0.14' of package 'log4net'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'log4net.2.0.14' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project WebServices\Paradise.WebServices: Unable to find version '5.0.11' of package 'LiteDB'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'LiteDB.5.0.11' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project Client\Paradise.Client: Unable to find version '2.2.1' of package 'Lib.Harmony'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Lib.Harmony.2.2.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project Realtime\Paradise.Realtime: Unable to find version '13.0.1' of package 'Newtonsoft.Json'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Newtonsoft.Json.13.0.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project WebServices\Paradise.WebServices.GUI: Unable to find version '2.0.14' of package 'log4net'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'log4net.2.0.14' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project WebServices\Paradise.WebServices.GUI: Unable to find version '13.0.1' of package 'Newtonsoft.Json'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Newtonsoft.Json.13.0.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project WebServices\Paradise.WebServices.ServiceHost: Unable to find version '2.0.14' of package 'log4net'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'log4net.2.0.14' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project WebServices\Paradise.WebServices: Unable to find version '13.0.1' of package 'Newtonsoft.Json'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Newtonsoft.Json.13.0.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project WebServices\Paradise.WebServices: Unable to find version '2.0.14' of package 'log4net'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'log4net.2.0.14' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.
1>------ Build started: Project: Paradise.Client, Configuration: Debug Any CPU ------
2>------ Build started: Project: Paradise.WebServices, Configuration: Debug Any CPU ------
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(1,7,1,13): error CS0246: The type or namespace name 'LiteDB' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(2,7,2,14): error CS0246: The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\ApplicationWebService.cs(1,7,1,14): error CS0246: The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\ApplicationWebService.cs(2,7,2,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\Legacy\RelationshipWebService_Legacy.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\Legacy\UserWebService_Legacy.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\Legacy\ShopWebService_Legacy.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\Legacy\PrivateMessageWebService_Legacy.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\Legacy\ModerationWebService_Legacy.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\Legacy\ClanWebService_Legacy.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\Legacy\AuthenticationWebService_Legacy.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\Legacy\ApplicationWebService_Legacy.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\ShopWebService.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\WebServiceBase.cs(1,7,1,14): error CS0246: The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(42,17,42,45): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(45,17,45,48): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(46,17,46,42): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(47,17,47,53): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(50,17,50,46): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(53,17,53,52): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(56,17,56,52): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(59,17,59,50): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(60,17,60,51): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(61,17,61,45): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(62,17,62,54): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(63,17,63,51): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(65,17,65,53): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(66,17,66,53): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(67,17,67,50): error CS0246: The type or namespace name 'ILiteCollection<>' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(33,19,33,23): error CS0246: The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\DatabaseManager.cs(37,18,37,30): error CS0246: The type or namespace name 'LiteDatabase' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\WebServiceBase.cs(14,29,14,33): error CS0246: The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\ApplicationWebService.cs(17,34,17,37): warning CS0108: 'ApplicationWebService.Log' hides inherited member 'WebServiceBase.Log'. Use the new keyword if hiding was intended.
2>C:\Users\90531\Desktop\Building\Paradise.WebServices\Services\ApplicationWebService.cs(17,29,17,33): error CS0246: The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\90531\Desktop\Building\Paradise.Client\Hooks\TrainingRoomHook.cs(1,7,1,17): error CS0246: The type or namespace name 'HarmonyLib' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\90531\Desktop\Building\Paradise.Client\Plugins\Custom Maps\CustomMapManager.cs(1,7,1,17): error CS0246: The type or namespace name 'HarmonyLib' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\90531\Desktop\Building\Paradise.Client\Hooks\CreateGamePanelGUIHook.cs(2,7,2,17): error CS0246: The type or namespace name 'HarmonyLib' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\90531\Desktop\Building\Paradise.Client\Hooks\WeaponControllerHook.cs(1,7,1,17): error CS0246: The type or namespace name 'HarmonyLib' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\90531\Desktop\Building\Paradise.Client\Hooks\BundleManagerHook.cs(1,7,1,17): error CS0246: The type or namespace name 'HarmonyLib' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\90531\Desktop\Building\Paradise.Client\Hooks\MenuPageManagerHook.cs(1,7,1,17): error CS0246: The type or namespace name 'HarmonyLib' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\90531\Desktop\Building\Paradise.Client\Plugins\Update\ParadiseUpdater.cs(7,7,7,17): error CS0246: The type or namespace name 'YamlDotNet' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\90531\Desktop\Building\Paradise.Client\Plugins\Update\ParadiseUpdater.cs(8,7,8,17): error CS0246: The type or namespace name 'YamlDotNet' could not be found (are you missing a using directive or an assembly reference?)
3>------ Build started: Project: Paradise.WebServices.GUI, Configuration: Debug Any CPU ------
4>------ Build started: Project: Paradise.WebServices.ServiceHost, Configuration: Debug Any CPU ------
5>------ Build started: Project: Paradise.Realtime, Configuration: Debug Any CPU ------
6>------ Build started: Project: Paradise.Client.Bootstrap, Configuration: Debug Any CPU ------
4>CSC : error CS0006: Metadata file 'C:\Users\90531\Desktop\Building\Paradise.WebServices\bin\Debug\Paradise.WebServices.dll' could not be found
5>CSC : error CS2001: Source file 'C:\Users\90531\Desktop\Building\Paradise.Realtime\Server\Game\Rooms\TeamEliminationGameRoom.cs' could not be found.
3>CSC : error CS0006: Metadata file 'C:\Users\90531\Desktop\Building\Paradise.WebServices\bin\Debug\Paradise.WebServices.dll' could not be found
6>CSC : error CS0006: Metadata file 'C:\Users\90531\Desktop\Building\Paradise.Client\bin\Debug\Paradise.Client.dll' could not be found
========== Build: 0 succeeded, 6 failed, 1 up-to-date, 0 skipped ==========
![zzzz (1) (1)](https://user-images.githubusercontent.com/107551249/173812945-a15ee4ed-fc56-4388-9ae1-d83b9db6cf36.png)

**Comment by karola3vax** [comment] 2022-06-15 11:09
1- Downloaded UberStrike.
2- Downloaded and patched game using ParadiseClient and UniversalUnityPatcher.
3- Downloaded ParadiseServer and Photon, used Photon's lib folder for necceseary files;

ExitGames.Logging.Log4Net.dll
ExitGamesLibs.dll
Photon.SocketServer.dll
UnityEngine.dll

Pasted these dll's to ParadiseServer, Paradise.Realtime's bin folder.
Back to our ParadiseServer, Paradise.WebServices, pasted UnityEngine.dll which is found in Uberstrike's root folder.
Back to our ParadiseServer, photon folder, pasted essential files using deploy/binWin64 from PhotonSDK we downloaded earlier.

Installed ParadiseService using InstallParadiseService.bat

4- Headed to UberStrike>\UberStrike_Data\ParadiseSettings.Client.xml and applied github.com/festivaldev/Paradise/wiki/Configuration-Client settings one by one.

5- Created 8080, 8081 port using "inetmgr" command on Windows. Otherwise It would give me connection error when game starts.

6- I gathered needed files for "AssemblyReferences"

7- Downloaded repository, got file named Paradise-master.zip that has Paradise.sln in it. I haven't touched anything.
Now, do I "rebuild" the Paradise.sln without touching anything or do I need to replace these files to for instance to photon root? I have 3 different folders.

Game works in general, just getting 8081 port Update: 404 Not Found error on launch of the game, pressing OK does the job.
No servers, exploring map.

**Comment by SniperGER** [comment] 2022-06-15 12:58
I've checked the build log, and it appears you need to restore missing NuGet packages. Visual Studio is usually supposed to do this automatically, which is why I didn't include this step in the documentation.

To restore the packages, right-click the "Paradise" solution in the Solution and select "Restore NuGet Packages". Once that's done, you should be able to build the projects.

As for the assembly copying stuff, I don't quite get what you're trying to achieve here when you only intend to play the game (once the server is back up, of course). You basically follow [the instructions](https://github.com/festivaldev/Paradise/wiki/Installation-Client) and that's it. There's no need to change any config file (or "create" ports using `inetmgr`) unless you're hosting your own server.

Again, the update error when launching the game (the update server is currently hardcoded to the main server and there's no option to redirect or disable update requests yet) and you only being able to explore maps are being caused by the server being offline, which I hope I can get fixed by the end of this week.

**Closed as completed** 2022-09-08 18:25 UTC
